<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT kurzusfelvetel (hallgato, kurzusok)>
<!ATTLIST kurzusfelvetel tanev CDATA #REQUIRED>
<!ATTLIST kurzusfelvetel egyetem CDATA #REQUIRED>


<!ELEMENT hallgato (hnev, szulev, szak)>
<!ELEMENT hnev (#PCDATA)>
<!ELEMENT szulev (#PCDATA)>
<!ELEMENT szak (#PCDATA)>
<!ATTLIST szak evf CDATA #REQUIRED>

<!ELEMENT kurzusok (kurzus*)>

<!ELEMENT kurzus (kurzusnev, hely, idopont+, (oktato | oraado)?)>
<!ATTLIST kurzus id ID #REQUIRED>
<!ATTLIST kurzus jovahagyas (igen | nem) "nem">
<!ATTLIST kurzus nyelv CDATA #IMPLIED>

<!ELEMENT kurzusnev (#PCDATA)>
<!ELEMENT hely (#PCDATA)>
<!ELEMENT idopont (#PCDATA)>
<!ELEMENT oktato (#PCDATA)>
<!ELEMENT oraado (#PCDATA)>